### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by San1tater1122** [San1tater1122/G10Culminating---Zombie-Wave-Encountering#4]
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.

**Comment by San1tater1122** [comment]
will be fixed

**Comment by MicroNeutron** [comment]
self give self pull issue yes ba

**Comment by San1tater1122** [comment]
**Duplicate of #[MicroNeutron](https://github.com/MicroNeutron)** 
just record I meet de bug that's all
